services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules


  server:
    build:
      context: ./Server 
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/carlog_db
    volumes:
      - ./Server:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carlog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Server/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck: # Pour s'assurer que la DB est prête avant de lancer l'API
      test: ["CMD-SHELL", "pg_isready -U user -d carlog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: